### PR TITLE
fix: closing pipe window

### LINKED ISSUE #1316: [bounty] pipe window turns black when full screen and closed
/bounty 100

1. put pipe full screen
2. close 

it's black and cannot close the window (macos 15.1)

### PR DESCRIPTION
**Pull request by tribhuwan-kumar**
/claim #1316
/closes #1316

https://github.com/user-attachments/assets/e0e86bfb-be97-46cd-abd0-2af58fcf14e0

brief description of the changes in this pr.

related issue: #

## how to test

add a few steps to test the pr in the most time efficient way.

1. 
2. 
3. 

if relevant add screenshots or screen captures to prove that this PR works to save us time.

if you think it can take more than 30 mins for us to review, we will pay between $20 and $200 for someone to review it for us, just ask in the pr.

### CODE REVIEW

File: screenpipe-app-tauri/src-tauri/src/commands.rs [hunk 1]
```diff
@@ -97,6 +97,19 @@ pub fn show_main_window(app_handle: &tauri::AppHandle<tauri::Wry>, overlay: bool
...
         }
+
+        // event listener for the window close event
+        let window_clone = window.clone();
+        window.on_window_event(move |event| {
+            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
+                if window_clone.is_fullscreen().unwrap_or(false) {
+                    let _ = window_clone.destroy().unwrap();
+                } else {
+                    let _ = window_clone.hide().unwrap();
```
Comment (louis030195) [inline screenpipe-app-tauri/src-tauri/src/commands.rs:108]: whats hide

Comment (louis030195) [reply screenpipe-app-tauri/src-tauri/src/commands.rs:108]: i guess it should always close

Comment (louis030195) [reply screenpipe-app-tauri/src-tauri/src/commands.rs:108]: pipe should not need to be open to work (using the cron featrue)

**Comment by louis030195** [comment]
/approve

gj
