### PR TITLE
fix: drop pipes runtime

### LINKED ISSUE #1149: [bounty] solve the windows process not dying issue
screenpipe backend cannot be killed anyhow 

few people claimed to have fixed but it's still broken, basically cannot kill processes on port 3030 or the backend unless rebooting, tried 40 commands given by claude 

/bounty 200 

refs:
- https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-server/src/auto_destruct.rs
- https://github.com/mediar-ai/screenpipe/blob/25e91f081111349843e95430fd0e0c0d7faa6783/screenpipe-app-tauri/components/dev-mode-settings.tsx#L147

### LINKED ISSUE #1322: [bounty] delete/purge pipe does not work on windows
/bounty 100

### PR DESCRIPTION
**Pull request by tribhuwan-kumar**
---
we don't need watchdog, if we use auto destruction and drop pipes runtime properly. i implemented this, like we talked about on discord. test in on windows and mac. working fine!

/claim #1149
/closes #1149
/claim #1322
/closes #1322
fix: #1351 
fix: #926 
fix: #1390 
related: #1345 

build https://drive.google.com/file/d/1AfXkE9mFy_R2se-WW7Fq58putUvcfdKS/view

please make sure you've not lauched your prior app build after starting your system

---

### CODE REVIEW

**Comment by tribhuwan-kumar** [comment]
@louis030195, https://jumpshare.com/s/fnZvWeUKnfEQ7Se4me7p

**Comment by neo773** [comment]
Not sure if it's related to this PR, but sidecar fails to spawn with error 

```
screenpipe_app: Failed to spawn initial sidecar: Camera permission denied
```


Full log
```
2025-02-18T13:21:41.251130Z  INFO screenpipe_app: Local data directory: /Users/neo/Library/Application Support/screenpipe
2025-02-18T13:21:41.251530Z  INFO screenpipe_app: data_dir: /Users/neo
2025-02-18T13:21:41.251620Z  INFO screenpipe_app: has_files: true
2025-02-18T13:21:41.251629Z  INFO screenpipe_app: use_dev_mode: false
2025-02-18T13:21:41.251634Z  INFO screenpipe_app: will start sidecar: true
2025-02-18T13:21:41.252101Z  INFO screenpipe_app::server: Server listening on 127.0.0.1:11435
2025-02-18T13:21:41.257248Z ERROR screenpipe_app::analytics: failed to check recording health: error sending request for url (http://localhost:3030/health)    
2025-02-18T13:21:41.257334Z ERROR screenpipe_app::tray: Failed to update tray menu: error sending request for url (http://localhost:3030/pipes/list): client error (Connect): tcp connect error: Connection refused (os error 61): Connection refused (os error 61)

2025-02-18T13:21:41.257934Z ERROR screenpipe_app: Failed to spawn initial sidecar: Camera permission denied
```

**Comment by tribhuwan-kumar** [comment]
> Tested on macOS, Not sure if it's related to this PR, but sidecar fails to spawn with error
> 
> ```
> screenpipe_app: Failed to spawn initial sidecar: Camera permission denied
> ```
> 
> Full log
> 
> ```
> 2025-02-18T13:21:41.251130Z  INFO screenpipe_app: Local data directory: /Users/neo/Library/Application Support/screenpipe
> 2025-02-18T13:21:41.251530Z  INFO screenpipe_app: data_dir: /Users/neo
> 2025-02-18T13:21:41.251620Z  INFO screenpipe_app: has_files: true
> 2025-02-18T13:21:41.251629Z  INFO screenpipe_app: use_dev_mode: false
> 2025-02-18T13:21:41.251634Z  INFO screenpipe_app: will start sidecar: true
> 2025-02-18T13:21:41.252101Z  INFO screenpipe_app::server: Server listening on 127.0.0.1:11435
> 2025-02-18T13:21:41.257248Z ERROR screenpipe_app::analytics: failed to check recording health: error sending request for url (http://localhost:3030/health)    
> 2025-02-18T13:21:41.257334Z ERROR screenpipe_app::tray: Failed to update tray menu: error sending request for url (http://localhost:3030/pipes/list): client error (Connect): tcp connect error: Connection refused (os error 61): Connection refused (os error 61)
> 
> 2025-02-18T13:21:41.257934Z ERROR screenpipe_app: Failed to spawn initial sidecar: Camera permission denied
> ```

my git head on `d0f98b20`

https://github.com/mediar-ai/screenpipe/pull/1348#discussion_r1959006433

**Comment by tribhuwan-kumar** [comment]
on mac: https://jumpshare.com/s/5IbLOSOrul82QPlClWiw

**Comment by tribhuwan-kumar** [comment]
@louis030195 could you review it?

**Comment by neo773** [comment]
@tribhuwan-kumar 
Could you merge with upstream/main ?

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar 
> Could you merge with upstream/main ?

merged it!

**Comment by tribhuwan-kumar** [comment]
it'll fix #1322 too!

**Comment by tribhuwan-kumar** [comment]
purging of pipes on windows

https://jumpshare.com/s/BdtgjvFMFkiFwlJ4Abcy

**Comment by tribhuwan-kumar** [comment]
<details>
<summary>
the watchdog is creating huge pile of logs and a single watchdog log file contains thousands of lines, <br> which can lead to this issue #1208

& [windows temp directory doesn't gets deleted automatically.](https://www.reddit.com/r/windows/comments/yfpbb1/why_arent_windows_temp_files_deleted/)
</summary>

```
-a----        18-02-2025  04:53 AM           1013 watchdog_16044_4016.ps1
-a----        18-02-2025  04:55 AM              0 watchdog_16168_18336.log
-a----        18-02-2025  04:55 AM              0 watchdog_16168_2392.log
-a----        18-02-2025  09:25 AM             85 watchdog_16212_11648.log
-a----        18-02-2025  09:25 AM             85 watchdog_16212_12564.log
-a----        17-02-2025  03:27 PM              0 watchdog_16340_16156.log
-a----        17-02-2025  03:27 PM           1014 watchdog_16340_16156.ps1
-a----        17-02-2025  03:27 PM              0 watchdog_16340_17268.log
-a----        17-02-2025  03:27 PM           1014 watchdog_16340_17268.ps1
-a----        16-02-2025  06:12 PM          61854 watchdog_16448_17864.log
-a----        16-02-2025  06:12 PM           1014 watchdog_16448_17864.ps1
-a----        17-02-2025  03:27 PM          60390 watchdog_16696_16732.log
-a----        17-02-2025  03:27 PM           1014 watchdog_16696_16732.ps1
-a----        17-02-2025  03:27 PM          53872 watchdog_16696_788.log
-a----        17-02-2025  03:27 PM           1012 watchdog_16696_788.ps1
-a----        17-02-2025  10:10 PM             85 watchdog_16780_17144.log
-a----        17-02-2025  10:10 PM           1073 watchdog_16780_17144.ps1
-a----        17-02-2025  10:10 PM             84 watchdog_16780_4680.log
-a----        17-02-2025  10:10 PM           1072 watchdog_16780_4680.ps1
-a----        17-02-2025  10:10 PM             85 watchdog_17016_12340.log
-a----        17-02-2025  10:10 PM           1073 watchdog_17016_12340.ps1
-a----        17-02-2025  10:10 PM             85 watchdog_17016_16752.log
-a----        17-02-2025  10:10 PM           1073 watchdog_17016_16752.ps1
-a----        18-02-2025  09:25 AM              0 watchdog_17224_460.log
-a----        18-02-2025  09:25 AM              0 watchdog_17224_8852.log
-a----        18-02-2025  09:27 AM              0 watchdog_17228_14232.log
-a----        18-02-2025  09:27 AM              0 watchdog_17228_16284.log
-a----        17-02-2025  10:15 PM              0 watchdog_17228_4388.log
-a----        17-02-2025  10:15 PM              0 watchdog_17228_4800.log
-a----        17-02-2025  03:30 PM              0 watchdog_17236_6888.log
-a----        17-02-2025  03:30 PM           1013 watchdog_17236_6888.ps1
-a----        17-02-2025  03:30 PM              0 watchdog_17236_9536.log
-a----        17-02-2025  03:30 PM           1013 watchdog_17236_9536.ps1
-a----        17-02-2025  03:19 PM              0 watchdog_17380_15780.log
-a----        17-02-2025  03:19 PM           1014 watchdog_17380_15780.ps1
-a----        17-02-2025  03:19 PM              0 watchdog_17380_16320.log
-a----        17-02-2025  03:19 PM           1014 watchdog_17380_16320.ps1
-a----        18-02-2025  07:44 AM              0 watchdog_17888_13108.log
-a----        18-02-2025  07:44 AM           1073 watchdog_17888_13108.ps1
-a----        18-02-2025  07:44 AM              0 watchdog_17888_14744.log
-a----        18-02-2025  07:44 AM           1073 watchdog_17888_14744.ps1
-a----        18-02-2025  04:52 AM              0 watchdog_18072_17356.log
-a----        18-02-2025  04:52 AM           1014 watchdog_18072_17356.ps1
-a----        18-02-2025  04:52 AM              0 watchdog_18072_2748.log
-a----        18-02-2025  04:52 AM           1013 watchdog_18072_2748.ps1
-a----        17-02-2025  10:08 PM             85 watchdog_18184_10288.log
-a----        17-02-2025  10:08 PM           1073 watchdog_18184_10288.ps1
-a----        17-02-2025  10:08 PM             84 watchdog_18184_4560.log
-a----        17-02-2025  10:08 PM           1072 watchdog_18184_4560.ps1
-a----        17-02-2025  09:20 PM             85 watchdog_18264_15396.log
-a----        17-02-2025  09:20 PM           1073 watchdog_18264_15396.ps1
-a----        17-02-2025  09:20 PM             85 watchdog_18264_16476.log
-a----        17-02-2025  09:20 PM           1073 watchdog_18264_16476.ps1
-a----        18-02-2025  09:27 AM              0 watchdog_18272_14084.log
-a----        18-02-2025  09:27 AM           1073 watchdog_18272_14084.ps1
-a----        18-02-2025  09:27 AM              0 watchdog_18272_18268.log
-a----        18-02-2025  09:27 AM           1073 watchdog_18272_18268.ps1
-a----        17-02-2025  03:31 PM          38325 watchdog_18280_1320.log
-a----        17-02-2025  03:31 PM           1013 watchdog_18280_1320.ps1
-a----        17-02-2025  03:31 PM          33215 watchdog_18280_8304.log
-a----        17-02-2025  03:31 PM           1013 watchdog_18280_8304.ps1
-a----        11-02-2025  05:10 PM              0 watchdog_18508_22120.log
-a----        11-02-2025  05:09 PM              0 watchdog_18508_2404.log
-a----        17-02-2025  04:59 PM              0 watchdog_18560_11868.log
-a----        17-02-2025  04:59 PM           1014 watchdog_18560_11868.ps1
-a----        17-02-2025  04:59 PM              0 watchdog_18592_18892.log
-a----        17-02-2025  04:59 PM           1014 watchdog_18592_18892.ps1
-a----        18-02-2025  07:40 AM             84 watchdog_18648_3416.log
-a----        18-02-2025  07:40 AM           1072 watchdog_18648_3416.ps1
-a----        18-02-2025  07:40 AM             84 watchdog_18648_6548.log
-a----        18-02-2025  07:40 AM           1072 watchdog_18648_6548.ps1
-a----        17-02-2025  04:59 PM              0 watchdog_18788_19268.log
-a----        17-02-2025  04:59 PM           1014 watchdog_18788_19268.ps1
-a----        18-02-2025  09:29 AM              0 watchdog_1896_7192.log
-a----        18-02-2025  09:29 AM           1071 watchdog_1896_7192.ps1
-a----        18-02-2025  09:29 AM              0 watchdog_1896_7688.log
-a----        18-02-2025  09:29 AM           1071 watchdog_1896_7688.ps1
-a----        15-02-2025  01:24 PM          67710 watchdog_19000_19228.log
-a----        18-02-2025  11:31 AM         132495 watchdog_1968_12300.log
-a----        18-02-2025  11:28 AM           1013 watchdog_1968_12300.ps1
-a----        18-02-2025  11:31 AM         108472 watchdog_1968_7192.log
-a----        18-02-2025  11:28 AM           1012 watchdog_1968_7192.ps1
-a----        18-02-2025  09:28 AM              0 watchdog_1988_16420.log
-a----        18-02-2025  09:28 AM           1072 watchdog_1988_16420.ps1
-a----        18-02-2025  09:28 AM              0 watchdog_1988_17112.log
-a----        18-02-2025  09:28 AM           1072 watchdog_1988_17112.ps1
-a----        17-02-2025  03:28 PM              0 watchdog_2016_17576.log
-a----        17-02-2025  03:28 PM           1013 watchdog_2016_17576.ps1
-a----        17-02-2025  03:28 PM              0 watchdog_2016_4284.log
-a----        17-02-2025  03:28 PM           1012 watchdog_2016_4284.ps1
-a----        13-02-2025  12:36 PM           8120 watchdog_20724_14512.log
-a----        13-02-2025  12:35 PM           1014 watchdog_20724_14512.ps1
-a----        13-02-2025  12:30 PM          98454 watchdog_20792_26288.log
-a----        18-02-2025  04:53 AM              0 watchdog_2096_16972.log
-a----        18-02-2025  04:53 AM           1013 watchdog_2096_16972.ps1
-a----        18-02-2025  04:53 AM              0 watchdog_2096_5748.log
-a----        18-02-2025  04:53 AM           1012 watchdog_2096_5748.ps1
-a----        11-02-2025  04:06 PM              0 watchdog_21068_20028.log
-a----        11-02-2025  04:06 PM              0 watchdog_21068_9900.log
-a----        11-02-2025  04:12 PM              0 watchdog_21820_14804.log
-a----        11-02-2025  04:12 PM              0 watchdog_21820_19704.log
-a----        13-02-2025  12:48 PM         582905 watchdog_2868_11508.log
-a----        13-02-2025  12:45 PM           1013 watchdog_2868_11508.ps1
-a----        14-02-2025  11:55 AM          40768 watchdog_3164_2088.log
-a----        11-02-2025  08:17 PM              0 watchdog_3164_5080.log
-a----        18-02-2025  05:06 AM          25550 watchdog_3444_17796.log
-a----        18-02-2025  06:49 AM         144144 watchdog_3640_7364.log
-a----        17-02-2025  03:21 PM          89790 watchdog_4052_13924.log
-a----        17-02-2025  03:19 PM           1013 watchdog_4052_13924.ps1
-a----        17-02-2025  03:21 PM          86632 watchdog_4052_1824.log
-a----        17-02-2025  03:19 PM           1012 watchdog_4052_1824.ps1
-a----        18-02-2025  09:29 AM              0 watchdog_428_11680.log
-a----        18-02-2025  09:29 AM           1071 watchdog_428_11680.ps1
-a----        18-02-2025  09:29 AM              0 watchdog_428_15576.log
-a----        18-02-2025  09:29 AM           1071 watchdog_428_15576.ps1
-a----        13-02-2025  12:49 PM              0 watchdog_4304_11756.log
-a----        13-02-2025  12:49 PM           1013 watchdog_4304_11756.ps1
-a----        13-02-2025  02:45 PM        4702660 watchdog_4304_12460.log
-a----        13-02-2025  12:51 PM           1013 watchdog_4304_12460.ps1
-a----        18-02-2025  04:52 AM              0 watchdog_4344_13460.log
-a----        18-02-2025  04:52 AM           1013 watchdog_4344_13460.ps1
-a----        18-02-2025  04:52 AM              0 watchdog_4344_15408.log
-a----        18-02-2025  04:52 AM           1013 watchdog_4344_15408.ps1
-a----        14-02-2025  10:37 AM         204400 watchdog_4364_17120.log
-a----        18-02-2025  09:28 AM              0 watchdog_4384_11064.log
-a----        18-02-2025  09:28 AM           1072 watchdog_4384_11064.ps1
-a----        18-02-2025  09:28 AM              0 watchdog_4384_14448.log
-a----        18-02-2025  09:28 AM           1072 watchdog_4384_14448.ps1
-a----        11-02-2025  08:04 PM              0 watchdog_440_8664.log
-a----        11-02-2025  07:58 PM        7644195 watchdog_4668_12416.log
-a----        11-02-2025  07:10 PM           1013 watchdog_4668_12416.ps1
-a----        18-02-2025  09:24 AM             84 watchdog_4924_11100.log
-a----        18-02-2025  09:24 AM           1072 watchdog_4924_11100.ps1
-a----        18-02-2025  09:24 AM             84 watchdog_4924_18916.log
-a----        18-02-2025  09:24 AM           1072 watchdog_4924_18916.ps1
-a----        18-02-2025  07:46 AM             84 watchdog_5476_14792.log
-a----        18-02-2025  07:46 AM             83 watchdog_5476_9152.log
-a----        13-02-2025  12:50 PM          11284 watchdog_5560_5744.log
-a----        13-02-2025  12:49 PM           1012 watchdog_5560_5744.ps1
-a----        18-02-2025  07:40 AM             84 watchdog_6024_15788.log
-a----        18-02-2025  07:40 AM           1072 watchdog_6024_15788.ps1
-a----        18-02-2025  07:40 AM             83 watchdog_6024_8812.log
-a----        18-02-2025  07:40 AM           1071 watchdog_6024_8812.ps1
-a----        17-02-2025  09:21 PM             84 watchdog_6156_12312.log
-a----        17-02-2025  09:21 PM           1072 watchdog_6156_12312.ps1
-a----        17-02-2025  09:21 PM             83 watchdog_6156_4928.log
-a----        17-02-2025  09:21 PM           1071 watchdog_6156_4928.ps1
-a----        13-02-2025  09:07 PM              0 watchdog_6572_13824.log
-a----        13-02-2025  09:07 PM           1013 watchdog_6572_13824.ps1
-a----        17-02-2025  10:08 PM             84 watchdog_6636_12912.log
-a----        17-02-2025  10:07 PM           1072 watchdog_6636_12912.ps1
-a----        17-02-2025  10:08 PM             84 watchdog_6636_13164.log
-a----        17-02-2025  10:07 PM           1072 watchdog_6636_13164.ps1
-a----        11-02-2025  08:39 PM              0 watchdog_6960_12888.log
-a----        11-02-2025  08:39 PM              0 watchdog_6960_7052.log
-a----        13-02-2025  09:46 PM              0 watchdog_6984_6320.log
-a----        13-02-2025  09:46 PM           1012 watchdog_6984_6320.ps1
-a----        18-02-2025  07:40 AM             84 watchdog_7208_13532.log
-a----        18-02-2025  07:40 AM           1072 watchdog_7208_13532.ps1
-a----        18-02-2025  07:40 AM             83 watchdog_7208_8760.log
-a----        18-02-2025  07:40 AM           1071 watchdog_7208_8760.ps1
-a----        11-02-2025  08:47 PM              0 watchdog_7732_18212.log
-a----        11-02-2025  08:45 PM              0 watchdog_7732_7792.log
-a----        14-02-2025  11:56 AM          14196 watchdog_7952_3168.log
-a----        14-02-2025  11:55 AM           1012 watchdog_7952_3168.ps1
-a----        18-02-2025  09:47 AM             84 watchdog_8320_13628.log
-a----        18-02-2025  09:47 AM             83 watchdog_8320_5156.log
-a----        16-02-2025  04:56 PM       47768645 watchdog_9072_10268.log
-a----        18-02-2025  07:46 AM             84 watchdog_9288_12932.log
-a----        18-02-2025  07:46 AM           1072 watchdog_9288_12932.ps1
-a----        18-02-2025  07:46 AM             84 watchdog_9288_15232.log
-a----        18-02-2025  07:46 AM           1072 watchdog_9288_15232.ps1
-a----        13-02-2025  12:43 PM              0 watchdog_9408_13100.log
-a----        11-02-2025  06:50 PM              0 watchdog_9604_13108.log
-a----        13-02-2025  09:35 PM              0 watchdog_9728_12028.log
-a----        13-02-2025  09:35 PM           1013 watchdog_9728_12028.ps1
-a----        16-02-2025  06:41 PM              0 watchdog_9948_8768.log
-a----        16-02-2025  06:41 PM           1012 watchdog_9948_8768.ps1
-a----        18-02-2025  04:51 AM              0 watchdog_9992_16964.log
-a----        18-02-2025  04:51 AM           1013 watchdog_9992_16964.ps1
-a----        18-02-2025  04:51 AM              0 watchdog_9992_17880.log
-a----        18-02-2025  04:51 AM           1013 watchdog_9992_17880.ps1
```
</details>


so this impl would be better apporach, you can test this [build](https://drive.google.com/file/d/1AfXkE9mFy_R2se-WW7Fq58putUvcfdKS/view?usp=sharing) in windows.
in this build:
- [x]  fixed purge of pipes
- [x] killing of pipes process
- [x] killing of screenpipe backend
- [x] port busy error
- [x] drop pipes runtime
- [x] removes watchdog dependency
- [x] auto destruction of backend

cc: @louis030195 

<br>
<br>

@AnsirU could you install this [build](https://drive.google.com/file/d/1AfXkE9mFy_R2se-WW7Fq58putUvcfdKS/view?usp=sharing) and share your experience? remember to skip the update dialog

**Comment by louis030195** [comment]
how do i know it works? can you do screen recording that close screenpipe app and restart and screenpipe properly starts? or other edge cases

**Comment by tribhuwan-kumar** [comment]
> how do i know it works? can you do screen recording that close screenpipe app and restart and screenpipe properly starts? or other edge cases

I've shared the screen recording

**Comment by tribhuwan-kumar** [comment]
> how do i know it works? can you do screen recording that close screenpipe app and restart and screenpipe properly starts? or other edge cases

https://jumpshare.com/s/3wuvL89KwFQYU7gasOKw 

@louis030195 its covers all the edge cases

**Comment by tribhuwan-kumar** [comment]
please view it & consider it merging, all the other prs about this issue are straight up copy paste of mine

https://github.com/user-attachments/assets/ad9338e9-01ad-4246-b0b6-f3ba4d79bb1e

File: screenpipe-server/src/pipe_manager.rs [hunk 1]
```diff
@@ -312,28 +343,109 @@ impl PipeManager {
...
+                let _ = tokio::process::Command::new("sh")
+                    .arg("-c")
+                    .arg(command)
+                    .output()
+                    .await;
+            }
+
             match handle.state {
                 PipeState::Port(port) => {
-                    tokio::task::spawn_blocking(move || {
```
Comment (louis030195) [inline screenpipe-server/src/pipe_manager.rs:317]: why this change, all works perfect on macos

Comment (tribhuwan-kumar) [reply screenpipe-server/src/pipe_manager.rs:317]: > why this change, all works perfect on macos

this splits the bun process on windows so this change

Comment (tribhuwan-kumar) [reply screenpipe-server/src/pipe_manager.rs:317]: > why this change, all works perfect on macos

this is for auto destruction of bun and node processes when the main process or given pid gets killed. on macos kill port doesn't seems working sometimes
